CREATE TABLE Abstract (
	ABKey INT(10) NOT NULL AUTO_INCREMENT,
	Atitle VARCHAR(30) NOT NULL,
	ABstatus CHAR(20) NOT NULL,
	ABPoster BLOB,
	Aadmin_ID INT(10) NOT NULL,
	Sstudent_ID	INT(10) NOT NULL,
	ABKey_doc INT(10) NOT NULL,
	
	PRIMARY KEY (ABKey),
	FOREIGN KEY (Aadmin_ID) REFERENCES Admin (Aadmin_ID) ON UPDATE CASCADE ON DELETE CASCADE,	
	FOREIGN KEY (Sstudent_ID) REFERENCES Student (Sstudent_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (ABKey_doc) REFERENCES ABDocument (ABKey_doc) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB;	

INSERT INTO Abstract VALUES	(0000000001,'Artificial Intelligence','Borderline','',0000000001,1,1), (0000000002,'Smart Cities','Weak Accept','',0000000001,1,2), (0000000003,'Reverse Engineering','Strongly Accept','',0000000001,1,3);